<a href="https://colab.research.google.com/github/l1f21bsee0018/DEEP-LEARNING/blob/main/EXP%20%234%20celoss_multiclass_classification_180325.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Ground truth labels (one-hot encoded)
y_true = np.array([
    [1, 0, 0, 0],  # Sample 1: Class 1
    [0, 1, 0, 1],  # Sample 2: Class 2
    [0, 0, 1, 0],  # Sample 3: Class 3
    [0, 1, 1, 1],  # Sample 4: Class 4
    [1, 0, 1, 0],  # Sample 5: Class 5
])

# Model predictions (logits)
logits = np.array([
    [2.0, 1.0, 0.1,0.2],  # Sample 1
    [0.5, 2.5, 0.2,0.1],  # Sample 2
    [0.1, 0.2, 3.0,1.0] ,  # Sample 3
    [0.5, 1.5, 0.1,0.3],  # Sample 4
    [0.3, 0.2, 2.5,1.0] ,  # Sample 5
])

# Softmax function
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))  # Numerical stability
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

# Compute softmax probabilities
probs = softmax(logits)
print("Softmax Probabilities:\n", probs)

# Compute log(probs)
log_probs = np.log(probs)
print("\nLog of Softmax Probabilities:\n", log_probs)

# Compute y_true * log(probs)
y_true_log_probs = y_true * log_probs
print("\ny_true * log(probs):\n", y_true_log_probs)

# Compute CE loss for each sample
ce_loss = -np.sum(y_true_log_probs, axis=-1)
print("\nCE Loss per Sample:", ce_loss)

# Average CE loss for the dataset
avg_ce_loss = np.mean(ce_loss)
print("\nAverage CE Loss for the Dataset:", avg_ce_loss)

Softmax Probabilities:
 [[0.59426642 0.2186184  0.08888361 0.09823158]
 [0.10203879 0.75397036 0.0755922  0.06839865]
 [0.04397746 0.04860261 0.79925282 0.10816711]
 [0.1920369  0.52201041 0.12872618 0.15722651]
 [0.07725824 0.06990614 0.69725663 0.15557898]]

Log of Softmax Probabilities:
 [[-0.52042755 -1.52042755 -2.42042755 -2.32042755]
 [-2.28240222 -0.28240222 -2.58240222 -2.68240222]
 [-3.12407797 -3.02407797 -0.22407797 -2.22407797]
 [-1.65006775 -0.65006775 -2.05006775 -1.85006775]
 [-2.56060174 -2.66060174 -0.36060174 -1.86060174]]

y_true * log(probs):
 [[-0.52042755 -0.         -0.         -0.        ]
 [-0.         -0.28240222 -0.         -2.68240222]
 [-0.         -0.         -0.22407797 -0.        ]
 [-0.         -0.65006775 -2.05006775 -1.85006775]
 [-2.56060174 -0.         -0.36060174 -0.        ]]

CE Loss per Sample: [0.52042755 2.96480444 0.22407797 4.55020326 2.92120348]

Average CE Loss for the Dataset: 2.2361433370793407
